name: CI

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 22]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
      
    - name: Install pnpm
      uses: pnpm/action-setup@v4
        
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        
    - name: Install dependencies
      run: pnpm install --frozen-lockfile
        
    - name: Build
      run: pnpm run build
      
    - name: Run tests
      run: pnpm test
      env:
        CI: true
        
    - name: Generate coverage report
      if: matrix.node-version == 22
      run: pnpm run coverage
      env:
        CI: true

    - name: Coveralls
      if: matrix.node-version == 22
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: docs/coverage/lcov.info 